[WIP] Setup base documentation website
klarna/electron-redux pull request #277
Opened 2020-10-29 00:07 UTC by antonioalmeida

Draft PR for #264

Progress:
- [x] Base docusaurus (v2) setup & config
- [x] Trigger docs deployment to `gh-pages` via Action (needs activation from repository maintainer for execution check)
- [ ] Documentation initial content

2020-11-07 22:28 UTC, antonioalmeida commented
Looks like the build is failing because I'm not a repository manager, hence, no key access.

2020-11-27 09:30 UTC, matmalkowski requested changes

2020-11-27 09:30 UTC, matmalkowski commented on .github/workflows/gh-pages.yml
> +    - alpha # remove this once v2 is released
Lets just scope it to `alpha` for now, since we don't have master docs

2020-11-27 09:30 UTC, matmalkowski commented on .github/workflows/gh-pages.yml
> +        npm install
should we use `yarn` instead?

2020-11-29 21:58 UTC, antonioalmeida commented
Reviews applied @matmalkowski ✅

2020-11-30 22:31 UTC, matmalkowski approved these changes

2020-11-30 22:35 UTC, merged

2020-12-03 16:11 UTC, matmalkowski commented
:tada: This PR is included in version 2.0.0-alpha.6 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/electron-redux/v/2.0.0-alpha.6)
- [GitHub release](https://github.com/klarna/electron-redux/releases/tag/v2.0.0-alpha.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: